export const candidateData = [
  {
    id: 'PP001',
    gender: 'Male',
    aboutMe: {
      surname: 'Panchal',
      name: 'Harsh',
      age: 27,
      height: "5'10\"",
      weight: '72 kg',
      qualification: 'Btech',
      stream: 'Mechanical Engineering',
      occupation: 'Design Engineer',
      incomeAnnual: '8,50,000 INR',
    },
    aboutMyFamily: {
      nativePlace: 'Ahmedabad',
      fatherName: 'Mahesh Panchal',
      fatherOccupation: 'Business',
      motherName: 'Kalpana Panchal',
      motherOccupation: 'Homemaker',
      brothers: '1',
      sisters: '0',
      incomeAnnual: '18,00,000 INR',
    },
    moreDetails: {
      dob: '1999-02-14',
      birthTime: '07:20 AM',
      birthPlace: 'Ahmedabad',
      spect: 'No',
      mangalShani: 'Mangal - No, Shani - No',
      disability: 'No',
      moreDetailsAboutMeAndMyChoice:
        'Family-oriented and looking for an educated partner with good values.',
    },
    contactAddress: {
      address: 'Satellite Road',
      city: 'Ahmedabad',
      state: 'Gujarat',
      country: 'India',
      pincode: '380015',
      phoneMobile: '+91 98250 10001',
      email: 'pp001@panchalparichay.in',
    },
  },
  {
    id: 'PP002',
    gender: 'Female',
    aboutMe: {
      surname: 'Suthar',
      name: 'Nidhi',
      age: 25,
      height: "5'4\"",
      weight: '56 kg',
      qualification: 'BCA',
      stream: 'Computer Applications',
      occupation: 'Software Analyst',
      incomeAnnual: '7,20,000 INR',
    },
    aboutMyFamily: {
      nativePlace: 'Vadodara',
      fatherName: 'Ramesh Suthar',
      fatherOccupation: 'Contractor',
      motherName: 'Asha Suthar',
      motherOccupation: 'Teacher',
      brothers: '0',
      sisters: '1',
      incomeAnnual: '15,00,000 INR',
    },
    moreDetails: {
      dob: '2001-08-06',
      birthTime: '09:45 PM',
      birthPlace: 'Vadodara',
      spect: 'No',
      mangalShani: 'Mangal - No, Shani - Yes',
      disability: 'No',
      moreDetailsAboutMeAndMyChoice:
        'Looking for a kind, respectful life partner with stable career.',
    },
    contactAddress: {
      address: 'Alkapuri',
      city: 'Vadodara',
      state: 'Gujarat',
      country: 'India',
      pincode: '390007',
      phoneMobile: '+91 98795 20002',
      email: 'pp002@panchalparichay.in',
    },
  },
  {
    id: 'PP003',
    gender: 'Male',
    aboutMe: {
      surname: 'Luhar',
      name: 'Amit',
      age: 32,
      height: "5'8\"",
      weight: '74 kg',
      qualification: 'Mtech',
      stream: 'Civil Engineering',
      occupation: 'Project Manager',
      incomeAnnual: '12,00,000 INR',
    },
    aboutMyFamily: {
      nativePlace: 'Rajkot',
      fatherName: 'Prakash Luhar',
      fatherOccupation: 'Retired',
      motherName: 'Hina Luhar',
      motherOccupation: 'Homemaker',
      brothers: '1',
      sisters: '1',
      incomeAnnual: '10,00,000 INR',
    },
    moreDetails: {
      dob: '1994-05-21',
      birthTime: '05:35 AM',
      birthPlace: 'Rajkot',
      spect: 'No',
      mangalShani: 'Mangal - Yes, Shani - No',
      disability: 'No',
      moreDetailsAboutMeAndMyChoice:
        'Prefer simple family and mutual respect in relationship.',
    },
    contactAddress: {
      address: 'Yagnik Road',
      city: 'Rajkot',
      state: 'Gujarat',
      country: 'India',
      pincode: '360001',
      phoneMobile: '+91 98989 30003',
      email: 'pp003@panchalparichay.in',
    },
  },
  {
    id: 'PP004',
    gender: 'Female',
    aboutMe: {
      surname: 'Mistry',
      name: 'Riya',
      age: 29,
      height: "5'5\"",
      weight: '58 kg',
      qualification: 'Btech',
      stream: 'Computer Science',
      occupation: 'UI Designer',
      incomeAnnual: '9,00,000 INR',
    },
    aboutMyFamily: {
      nativePlace: 'Surat',
      fatherName: 'Jignesh Mistry',
      fatherOccupation: 'Business',
      motherName: 'Pooja Mistry',
      motherOccupation: 'Homemaker',
      brothers: '0',
      sisters: '1',
      incomeAnnual: '22,00,000 INR',
    },
    moreDetails: {
      dob: '1997-11-13',
      birthTime: '11:10 AM',
      birthPlace: 'Surat',
      spect: 'No',
      mangalShani: 'Mangal - No, Shani - No',
      disability: 'No',
      moreDetailsAboutMeAndMyChoice:
        'Interested in a caring partner with modern thinking and values.',
    },
    contactAddress: {
      address: 'Adajan',
      city: 'Surat',
      state: 'Gujarat',
      country: 'India',
      pincode: '395009',
      phoneMobile: '+91 98251 40004',
      email: 'pp004@panchalparichay.in',
    },
  },
  {
    id: 'PP005',
    gender: 'Male',
    aboutMe: {
      surname: 'Panchal',
      name: 'Kunal',
      age: 38,
      height: "5'9\"",
      weight: '77 kg',
      qualification: 'Mtech',
      stream: 'Industrial Engineering',
      occupation: 'Operations Head',
      incomeAnnual: '16,00,000 INR',
    },
    aboutMyFamily: {
      nativePlace: 'Bhavnagar',
      fatherName: 'Dinesh Panchal',
      fatherOccupation: 'Business',
      motherName: 'Bharti Panchal',
      motherOccupation: 'Homemaker',
      brothers: '1',
      sisters: '2',
      incomeAnnual: '20,00,000 INR',
    },
    moreDetails: {
      dob: '1988-01-05',
      birthTime: '02:30 PM',
      birthPlace: 'Bhavnagar',
      spect: 'No',
      mangalShani: 'Mangal - No, Shani - Yes',
      disability: 'No',
      moreDetailsAboutMeAndMyChoice:
        'Looking for compatible partner focused on family growth.',
    },
    contactAddress: {
      address: 'Waghawadi Road',
      city: 'Bhavnagar',
      state: 'Gujarat',
      country: 'India',
      pincode: '364002',
      phoneMobile: '+91 90990 50005',
      email: 'pp005@panchalparichay.in',
    },
  },
  {
    id: 'PP006',
    gender: 'Female',
    aboutMe: {
      surname: 'Suthar',
      name: 'Mitali',
      age: 31,
      height: "5'3\"",
      weight: '55 kg',
      qualification: 'Mtech',
      stream: 'Information Technology',
      occupation: 'Tech Lead',
      incomeAnnual: '18,50,000 INR',
    },
    aboutMyFamily: {
      nativePlace: 'Anand',
      fatherName: 'Ajay Suthar',
      fatherOccupation: 'Farmer',
      motherName: 'Varsha Suthar',
      motherOccupation: 'Homemaker',
      brothers: '1',
      sisters: '0',
      incomeAnnual: '14,00,000 INR',
    },
    moreDetails: {
      dob: '1995-07-09',
      birthTime: '06:10 PM',
      birthPlace: 'Anand',
      spect: 'No',
      mangalShani: 'Mangal - Yes, Shani - No',
      disability: 'No',
      moreDetailsAboutMeAndMyChoice:
        'Prefer partner from supportive family with positive mindset.',
    },
    contactAddress: {
      address: 'Vallabh Vidyanagar',
      city: 'Anand',
      state: 'Gujarat',
      country: 'India',
      pincode: '388120',
      phoneMobile: '+91 94260 60006',
      email: 'pp006@panchalparichay.in',
    },
  },
  {
    id: 'PP007',
    gender: 'Male',
    aboutMe: {
      surname: 'Luhar',
      name: 'Rohan',
      age: 24,
      height: "5'11\"",
      weight: '69 kg',
      qualification: 'BCA',
      stream: 'Computer Applications',
      occupation: 'QA Engineer',
      incomeAnnual: '6,20,000 INR',
    },
    aboutMyFamily: {
      nativePlace: 'Nadiad',
      fatherName: 'Sanjay Luhar',
      fatherOccupation: 'Shop Owner',
      motherName: 'Monika Luhar',
      motherOccupation: 'Homemaker',
      brothers: '0',
      sisters: '1',
      incomeAnnual: '11,00,000 INR',
    },
    moreDetails: {
      dob: '2002-09-18',
      birthTime: '10:30 AM',
      birthPlace: 'Nadiad',
      spect: 'No',
      mangalShani: 'Mangal - No, Shani - No',
      disability: 'No',
      moreDetailsAboutMeAndMyChoice:
        'Seeking understanding partner and progressive family.',
    },
    contactAddress: {
      address: 'College Road',
      city: 'Nadiad',
      state: 'Gujarat',
      country: 'India',
      pincode: '387001',
      phoneMobile: '+91 97129 70007',
      email: 'pp007@panchalparichay.in',
    },
  },
  {
    id: 'PP008',
    gender: 'Female',
    aboutMe: {
      surname: 'Mistry',
      name: 'Kavya',
      age: 35,
      height: "5'6\"",
      weight: '59 kg',
      qualification: 'Btech',
      stream: 'Electronics',
      occupation: 'Product Specialist',
      incomeAnnual: '14,00,000 INR',
    },
    aboutMyFamily: {
      nativePlace: 'Mumbai',
      fatherName: 'Hitesh Mistry',
      fatherOccupation: 'Retired Engineer',
      motherName: 'Anita Mistry',
      motherOccupation: 'Homemaker',
      brothers: '1',
      sisters: '0',
      incomeAnnual: '17,00,000 INR',
    },
    moreDetails: {
      dob: '1991-03-25',
      birthTime: '04:40 AM',
      birthPlace: 'Mumbai',
      spect: 'No',
      mangalShani: 'Mangal - No, Shani - No',
      disability: 'No',
      moreDetailsAboutMeAndMyChoice:
        'Looking for family-oriented partner, open to relocation.',
    },
    contactAddress: {
      address: 'Andheri East',
      city: 'Mumbai',
      state: 'Maharashtra',
      country: 'India',
      pincode: '400069',
      phoneMobile: '+91 98190 80008',
      email: 'pp008@panchalparichay.in',
    },
  },
  {
    id: 'PP009',
    gender: 'Male',
    aboutMe: {
      surname: 'Panchal',
      name: 'Jay',
      age: 42,
      height: "5'7\"",
      weight: '76 kg',
      qualification: 'Btech',
      stream: 'Production Engineering',
      occupation: 'Plant Supervisor',
      incomeAnnual: '11,00,000 INR',
    },
    aboutMyFamily: {
      nativePlace: 'Pune',
      fatherName: 'Bharat Panchal',
      fatherOccupation: 'Retired',
      motherName: 'Kokila Panchal',
      motherOccupation: 'Homemaker',
      brothers: '2',
      sisters: '0',
      incomeAnnual: '12,00,000 INR',
    },
    moreDetails: {
      dob: '1984-12-02',
      birthTime: '08:55 PM',
      birthPlace: 'Pune',
      spect: 'No',
      mangalShani: 'Mangal - Yes, Shani - Yes',
      disability: 'No',
      moreDetailsAboutMeAndMyChoice:
        'Simple lifestyle and looking for understanding life partner.',
    },
    contactAddress: {
      address: 'Kothrud',
      city: 'Pune',
      state: 'Maharashtra',
      country: 'India',
      pincode: '411038',
      phoneMobile: '+91 98500 90009',
      email: 'pp009@panchalparichay.in',
    },
  },
  {
    id: 'PP010',
    gender: 'Female',
    aboutMe: {
      surname: 'Suthar',
      name: 'Priya',
      age: 28,
      height: "5'2\"",
      weight: '53 kg',
      qualification: 'BCA',
      stream: 'Computer Applications',
      occupation: 'Web Developer',
      incomeAnnual: '8,10,000 INR',
    },
    aboutMyFamily: {
      nativePlace: 'Jaipur',
      fatherName: 'Govind Suthar',
      fatherOccupation: 'Architect',
      motherName: 'Neeta Suthar',
      motherOccupation: 'Teacher',
      brothers: '1',
      sisters: '1',
      incomeAnnual: '19,00,000 INR',
    },
    moreDetails: {
      dob: '1998-06-30',
      birthTime: '03:15 PM',
      birthPlace: 'Jaipur',
      spect: 'No',
      mangalShani: 'Mangal - No, Shani - No',
      disability: 'No',
      moreDetailsAboutMeAndMyChoice:
        'Looking for supportive and educated partner from good family.',
    },
    contactAddress: {
      address: 'Mansarovar',
      city: 'Jaipur',
      state: 'Rajasthan',
      country: 'India',
      pincode: '302020',
      phoneMobile: '+91 95499 10010',
      email: 'pp010@panchalparichay.in',
    },
  },
  {
    id: 'PP011',
    gender: 'Male',
    aboutMe: {
      surname: 'Mistry',
      name: 'Nirav',
      age: 33,
      height: "6'0\"",
      weight: '80 kg',
      qualification: 'Mtech',
      stream: 'Robotics',
      occupation: 'Automation Engineer',
      incomeAnnual: '95,000 USD',
    },
    aboutMyFamily: {
      nativePlace: 'Ahmedabad',
      fatherName: 'Kirit Mistry',
      fatherOccupation: 'Business',
      motherName: 'Rekha Mistry',
      motherOccupation: 'Homemaker',
      brothers: '0',
      sisters: '1',
      incomeAnnual: '24,00,000 INR',
    },
    moreDetails: {
      dob: '1993-04-16',
      birthTime: '01:05 PM',
      birthPlace: 'Ahmedabad',
      spect: 'No',
      mangalShani: 'Mangal - No, Shani - Yes',
      disability: 'No',
      moreDetailsAboutMeAndMyChoice:
        'Based in USA, seeking partner comfortable with international life.',
    },
    contactAddress: {
      address: 'Fremont Boulevard',
      city: 'Fremont',
      state: 'California',
      country: 'Usa',
      pincode: '94538',
      phoneMobile: '+1 510 555 0011',
      email: 'pp011@panchalparichay.in',
    },
  },
  {
    id: 'PP012',
    gender: 'Female',
    aboutMe: {
      surname: 'Luhar',
      name: 'Hetal',
      age: 36,
      height: "5'5\"",
      weight: '60 kg',
      qualification: 'Btech',
      stream: 'Electrical Engineering',
      occupation: 'Senior Consultant',
      incomeAnnual: '88,000 USD',
    },
    aboutMyFamily: {
      nativePlace: 'Bhuj',
      fatherName: 'Nilesh Luhar',
      fatherOccupation: 'Business',
      motherName: 'Meena Luhar',
      motherOccupation: 'Homemaker',
      brothers: '1',
      sisters: '0',
      incomeAnnual: '16,00,000 INR',
    },
    moreDetails: {
      dob: '1990-10-11',
      birthTime: '12:45 AM',
      birthPlace: 'Bhuj',
      spect: 'No',
      mangalShani: 'Mangal - Yes, Shani - No',
      disability: 'No',
      moreDetailsAboutMeAndMyChoice:
        'Open-minded and family-focused, interested in compatible match.',
    },
    contactAddress: {
      address: 'Jersey City Heights',
      city: 'Jersey City',
      state: 'New Jersey',
      country: 'Usa',
      pincode: '07306',
      phoneMobile: '+1 201 555 0012',
      email: 'pp012@panchalparichay.in',
    },
  },
]

